version: '3.8'
services: 
  npm:
    build: ./
    stdin_open: true
    tty: true 
    volumes: 
    #bind mount da PASTA EM QUE O docker-compose.yaml ESTÁ, bindada à pasta 'app' DENTRO DO CONTAINER...
      - ./:/app