apiVersion: v1
kind: Service
metadata:
  name: communication-app-service
spec:
  selector:
    app: communication
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: LoadBalancer
