apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: 'TCP'
      port: 80  ## port que 'faces the outside world' 
      targetPort: 80 ###port interno, dentro desse 'service ip address', a que podemos enviar requests, INTERNAMENTE...
  type: ClusterIP ## colocamos isto pq 'PRECISAMOS DE 1 IP FIXO, MAS NÃO PRECISAMOS QUE ESSE IP/POD SEJA REACHABLE LÁ NO MUNDO EXTERNO AO NOSSO CLUSTER'....
