apiVersion: v1 # diferente de 'apps/v1', usada no 'deployment.yaml' 
kind: Service
metadata:  # necessário
  name: backend  # podemos escolher qualquer nome
spec:    # é o mais importante
## vc vai SELECIONAR OS __ PODS, E NÃO OS DEPLOYMENTS EM SI...
  selector:   # É ESSENCIAL.... E O SELECTOR DE 'Service's _FUNCIONA DE FORMA 1 POUCO DISTINTA DAQUELA VISTA NO SELECTOR DOS OBJECTS 'Deployment'... (pq aqui não há a decisão entre 'matchLabels' e 'matchExpressions', pq SEMPRE SERÁ A OPÇÃO 'matchLabels'...)
    app: second-app ##? OBS: podemos selecionar PODS QUE PERTENÇAM A 2 DEPLOYMENTS DISTINTOS _ NESSE MESMO SERVICE__ ...
  ports: # é uma lista, pq podemos expor vários ports...
    - protocol: 'TCP' ### é o default... 'conexão direta', maior confiabilidade, menor velocidade
      port: 80  ## port externa, alcançável pelo 'external world'...
      targetPort: 8080 ## port interna, dos nossos pods/containers...
    # - protocol: 'UDP'   ### como adicionar mais ports...
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer ## pode ser também 'ClusterIP' (é o default) e 'NodePort'